### ISSUE TITLE
Not working with api 23

### ISSUE THREAD

**Issue by nguyendinhduc** [Piasy/RxScreenshotDetector#3]
It not working working with api 23 ( my device is nexus 5 api 23), please help me!

**Comment by Piasy** [comment]
Actually the gif in README is recorded on a Nexus 5X, API 23.

Could you please provide logcat output with tag `RxScreenshotDetector` and `MainActivity`?

**Comment by nguyendinhduc** [comment]
D/RxScreenshotDetector: onChange: false, content://media/external/images/media
D/RxScreenshotDetector: path: /storage/emulated/0/1469335123191.jpg, dateAdded: 1469854648, currentTime: 1467510657

**Comment by Piasy** [comment]
The screenshot detection works based on media observer, when a new photo is added, [if the path contains several keywords, i.e. `screenshot`](https://github.com/Piasy/RxScreenshotDetector/blob/master/rxscreenshotdetector/src/main/java/com/github/piasy/rxscreenshotdetector/RxScreenshotDetector.java#L141), and the newly added photo's add [time and current time are in 10 seconds](https://github.com/Piasy/RxScreenshotDetector/blob/master/rxscreenshotdetector/src/main/java/com/github/piasy/rxscreenshotdetector/RxScreenshotDetector.java#L146), this newly added photo will be treated as a screenshot.

From the log you provided, the path is `/storage/emulated/0/1469335123191.jpg`, not matched, and the time fails to match too. **I guess the main reason is that your phone's time is not right,** please correct your phone's time, and delete all wrong time images, (or set your phone time later then those images), and try again?

**Comment by nguyendinhduc** [comment]
I understand but
 unfortunately, the user to change the time suddenly in your phone and take screen shot, then app capture event screen shot is not correct!

**Comment by Piasy** [comment]
Yes of course, this library only work as best effort, it won't (and can't I think) cover corner cases. Good luck with it :)

**Comment by nguyendinhduc** [comment]
Thank you very much, you are too enthusiastic!

**Comment by Piasy** [comment]
My pleasure :)
