### ISSUE TITLE
RxScreenshotDetector 简介的链接失效

### ISSUE THREAD

**Issue by xingstarx** [Piasy/RxScreenshotDetector#4]
`http://blog.piasy.com/Android-Screenshot-Detector/` 应该改为`http://blog.piasy.com/2016/01/29/Android-Screenshot-Detector/` 吧

同理https://github.com/Piasy/RxComboDetector 这个项目也是一样的问题

这个功能挺棒的, ^-^

**Comment by Piasy** [comment]
噢谢谢指出！之前博客换主题，导致链接规则发生了变化

**Comment by Piasy** [comment]
fixed!

**Comment by xingstarx** [comment]
好速度,Very Great!
